/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package snake.UI.Widget;

import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.Base64;
import javax.swing.ImageIcon;
import snake.pessoa.Pessoa;

/**
 *
 * @author luan
 */
public class ItemJogoAnterior extends javax.swing.JPanel {
    Pessoa pessoa;
    String nomeFase;
    /**
     * Creates new form ItemJogoAnterior
     */
    public ItemJogoAnterior(Pessoa p) throws Exception {
        initComponents();
        this.pessoa = p;
        
        txtNome.setText("Nome: "+pessoa.getNome());
        txtData.setText("Data: "+pessoa.getData());
        
        
        
        if(pessoa.getNivel() != -1){
            setIconImg(pessoa.getNivel());
            txtFase.setText("Nível: "+pessoa.getNivel()+" Nome: "+nomeFase);
        }
        else{
            txtFase.setText("Noob!!!");
        }
    }

    public Pessoa getPessoa() {
        return pessoa;
    }

    private void setIconImg(int fase) throws Exception{
        ImageIcon imgPreview = new ImageIcon(Base64.getDecoder().decode(buscarImg(fase)));
        imgPreview = new ImageIcon(imgPreview.getImage().getScaledInstance(120, 89, Image.SCALE_DEFAULT));
        
        jLabel1.setIcon(imgPreview);
    }
    
    //aproveitando essa funcao para pegar o nome da fase tbm
    private String buscarImg(int nivel) throws Exception{
        FileReader fr = new FileReader(new File("lvl\\"+nivel+".lvl"));
        BufferedReader br = new BufferedReader(fr);
        
        String s = br.readLine();
        String[] v = s.split(":");
        while(!v[0].equals("img_preview")){
            if(v[0].equals("name"))
                nomeFase = v[1];
            
            s = br.readLine();
            v = s.split(":");
        }
        br.close();
        fr.close();
        
        if(v[0].equals("img_preview"))
            return v[1];
        else
            return null;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNome = new javax.swing.JLabel();
        txtData = new javax.swing.JLabel();
        txtFase = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMaximumSize(new java.awt.Dimension(180, 207));
        setMinimumSize(new java.awt.Dimension(180, 207));

        txtNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNome.setText("Nome");

        txtData.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtData.setText("Data");

        txtFase.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtFase.setText("Fase");

        jLabel1.setPreferredSize(new java.awt.Dimension(120, 89));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtData, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(txtFase, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(txtNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFase)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel txtData;
    private javax.swing.JLabel txtFase;
    private javax.swing.JLabel txtNome;
    // End of variables declaration//GEN-END:variables
}
